name: Codeboard Android CI

on:
  push:
    branches:
    - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Set Gradle permissions
      run: chmod a+x ./gradlew
    - name: Build with Gradle
      run: ./gradlew build
